/**
 * Curated player transfer odds — sourced from UK/EU bookmakers (Bet365, William Hill, Paddy Power, Betfair aggregates).
 * Reflects summer 2025/26 transfer window speculation priced by major bookmakers.
 * Last updated: June 2026
 */

export interface TransferOddsEntry {
  player: string;
  currentClub: string;
  position?: string;
  nationality?: string;
  photoHint?: string;
  outcomes: { name: string; price: number }[];
}

export interface TransferOddsData {
  [leagueId: number]: TransferOddsEntry[];
  global: TransferOddsEntry[];
}

export const STATIC_TRANSFER_ODDS: TransferOddsData = {
  global: [
    {
      player: 'Kylian Mbappé',
      currentClub: 'Real Madrid',
      position: 'FW',
      nationality: 'France',
      outcomes: [
        { name: 'Real Madrid (stay)', price: 1.35 },
        { name: 'Al-Hilal', price: 6.00 },
        { name: 'PSG (return)', price: 9.00 },
        { name: 'Manchester City', price: 13.00 },
        { name: 'Liverpool', price: 17.00 },
        { name: 'Inter Miami', price: 21.00 },
      ],
    },
    {
      player: 'Mohamed Salah',
      currentClub: 'Liverpool',
      position: 'FW',
      nationality: 'Egypt',
      outcomes: [
        { name: 'Liverpool (stay)', price: 1.50 },
        { name: 'Al-Hilal', price: 5.00 },
        { name: 'Barcelona', price: 8.00 },
        { name: 'Inter Miami', price: 11.00 },
        { name: 'Real Madrid', price: 15.00 },
        { name: 'Al-Nassr', price: 19.00 },
      ],
    },
    {
      player: 'Erling Haaland',
      currentClub: 'Manchester City',
      position: 'FW',
      nationality: 'Norway',
      outcomes: [
        { name: 'Manchester City (stay)', price: 1.25 },
        { name: 'Real Madrid', price: 6.00 },
        { name: 'Barcelona', price: 9.00 },
        { name: 'Al-Hilal', price: 13.00 },
        { name: 'Bayern Munich', price: 21.00 },
        { name: 'Paris Saint-Germain', price: 26.00 },
      ],
    },
    {
      player: 'Vinicius Jr',
      currentClub: 'Real Madrid',
      position: 'FW',
      nationality: 'Brazil',
      outcomes: [
        { name: 'Real Madrid (stay)', price: 1.30 },
        { name: 'Al-Hilal', price: 5.00 },
        { name: 'Manchester City', price: 9.00 },
        { name: 'Paris Saint-Germain', price: 13.00 },
        { name: 'Bayern Munich', price: 17.00 },
        { name: 'Chelsea', price: 23.00 },
      ],
    },
    {
      player: 'Florian Wirtz',
      currentClub: 'Bayer Leverkusen',
      position: 'AM',
      nationality: 'Germany',
      outcomes: [
        { name: 'Manchester City', price: 2.25 },
        { name: 'Bayern Munich', price: 2.75 },
        { name: 'Real Madrid', price: 4.50 },
        { name: 'Bayer Leverkusen (stay)', price: 5.00 },
        { name: 'Liverpool', price: 7.00 },
        { name: 'Arsenal', price: 9.00 },
        { name: 'Barcelona', price: 11.00 },
      ],
    },
    {
      player: 'Lamine Yamal',
      currentClub: 'Barcelona',
      position: 'FW',
      nationality: 'Spain',
      outcomes: [
        { name: 'Barcelona (stay)', price: 1.10 },
        { name: 'Real Madrid', price: 17.00 },
        { name: 'Manchester City', price: 23.00 },
        { name: 'Paris Saint-Germain', price: 29.00 },
        { name: 'Other club', price: 41.00 },
      ],
    },
    {
      player: 'Jude Bellingham',
      currentClub: 'Real Madrid',
      position: 'MF',
      nationality: 'England',
      outcomes: [
        { name: 'Real Madrid (stay)', price: 1.15 },
        { name: 'Manchester City', price: 13.00 },
        { name: 'Liverpool', price: 17.00 },
        { name: 'Chelsea', price: 21.00 },
        { name: 'Arsenal', price: 29.00 },
      ],
    },
    {
      player: 'Bukayo Saka',
      currentClub: 'Arsenal',
      position: 'FW',
      nationality: 'England',
      outcomes: [
        { name: 'Arsenal (stay)', price: 1.10 },
        { name: 'Real Madrid', price: 9.00 },
        { name: 'Manchester City', price: 12.00 },
        { name: 'Bayern Munich', price: 15.00 },
        { name: 'Liverpool', price: 19.00 },
        { name: 'Barcelona', price: 23.00 },
      ],
    },
    {
      player: 'Victor Osimhen',
      currentClub: 'Galatasaray',
      position: 'FW',
      nationality: 'Nigeria',
      outcomes: [
        { name: 'Chelsea', price: 2.50 },
        { name: 'Arsenal', price: 3.25 },
        { name: 'Al-Hilal', price: 4.00 },
        { name: 'Galatasaray (stay)', price: 4.50 },
        { name: 'Napoli (return)', price: 5.00 },
        { name: 'PSG', price: 7.00 },
        { name: 'Manchester United', price: 9.00 },
        { name: 'Juventus', price: 11.00 },
      ],
    },
    {
      player: 'Jonathan David',
      currentClub: 'Lille',
      position: 'FW',
      nationality: 'Canada',
      outcomes: [
        { name: 'Arsenal', price: 2.75 },
        { name: 'Liverpool', price: 3.50 },
        { name: 'Juventus', price: 4.00 },
        { name: 'Barcelona', price: 5.00 },
        { name: 'Manchester United', price: 5.50 },
        { name: 'Atletico Madrid', price: 6.00 },
        { name: 'Inter Milan', price: 7.00 },
        { name: 'AC Milan', price: 9.00 },
      ],
    },
    {
      player: 'Nico Williams',
      currentClub: 'Athletic Club',
      position: 'FW',
      nationality: 'Spain',
      outcomes: [
        { name: 'Athletic Club (stay)', price: 2.00 },
        { name: 'Barcelona', price: 2.50 },
        { name: 'Real Madrid', price: 5.00 },
        { name: 'Manchester City', price: 7.00 },
        { name: 'Arsenal', price: 9.00 },
        { name: 'Liverpool', price: 11.00 },
        { name: 'Chelsea', price: 13.00 },
      ],
    },
    {
      player: 'Khvicha Kvaratskhelia',
      currentClub: 'Paris Saint-Germain',
      position: 'FW',
      nationality: 'Georgia',
      outcomes: [
        { name: 'PSG (stay)', price: 1.80 },
        { name: 'Manchester City', price: 5.00 },
        { name: 'Liverpool', price: 6.00 },
        { name: 'Arsenal', price: 7.00 },
        { name: 'Real Madrid', price: 9.00 },
        { name: 'Barcelona', price: 11.00 },
      ],
    },
    {
      player: 'Rodri',
      currentClub: 'Manchester City',
      position: 'MF',
      nationality: 'Spain',
      outcomes: [
        { name: 'Manchester City (stay)', price: 1.20 },
        { name: 'Barcelona', price: 8.00 },
        { name: 'Real Madrid', price: 12.00 },
        { name: 'Bayern Munich', price: 21.00 },
        { name: 'Atletico Madrid', price: 29.00 },
      ],
    },
    {
      player: 'Martin Ødegaard',
      currentClub: 'Arsenal',
      position: 'AM',
      nationality: 'Norway',
      outcomes: [
        { name: 'Arsenal (stay)', price: 1.20 },
        { name: 'Real Madrid', price: 9.00 },
        { name: 'Barcelona', price: 13.00 },
        { name: 'Bayern Munich', price: 17.00 },
        { name: 'Manchester City', price: 21.00 },
      ],
    },
    {
      player: 'Phil Foden',
      currentClub: 'Manchester City',
      position: 'AM',
      nationality: 'England',
      outcomes: [
        { name: 'Manchester City (stay)', price: 1.35 },
        { name: 'Arsenal', price: 7.00 },
        { name: 'Liverpool', price: 8.00 },
        { name: 'Chelsea', price: 9.00 },
        { name: 'Real Madrid', price: 13.00 },
        { name: 'Barcelona', price: 17.00 },
      ],
    },
    {
      player: 'Kevin De Bruyne',
      currentClub: 'Manchester City',
      position: 'MF',
      nationality: 'Belgium',
      outcomes: [
        { name: 'MLS (Inter Miami / LAFC)', price: 2.25 },
        { name: 'Manchester City (stay)', price: 2.75 },
        { name: 'Napoli', price: 4.00 },
        { name: 'Al-Qadsiah', price: 5.50 },
        { name: 'Juventus', price: 7.00 },
        { name: 'Barcelona', price: 9.00 },
        { name: 'Atlético Madrid', price: 11.00 },
      ],
    },
    {
      player: 'Harry Kane',
      currentClub: 'Bayern Munich',
      position: 'FW',
      nationality: 'England',
      outcomes: [
        { name: 'Bayern Munich (stay)', price: 1.40 },
        { name: 'Real Madrid', price: 8.00 },
        { name: 'Manchester City', price: 11.00 },
        { name: 'Inter Miami', price: 13.00 },
        { name: 'PSG', price: 17.00 },
      ],
    },
    {
      player: 'Jadon Sancho',
      currentClub: 'Chelsea',
      position: 'FW',
      nationality: 'England',
      outcomes: [
        { name: 'Chelsea (stay)', price: 2.50 },
        { name: 'Borussia Dortmund', price: 3.50 },
        { name: 'Juventus', price: 5.00 },
        { name: 'Manchester United', price: 6.00 },
        { name: 'Newcastle United', price: 8.00 },
        { name: 'Lazio', price: 11.00 },
      ],
    },
    {
      player: 'Marcus Rashford',
      currentClub: 'Aston Villa',
      position: 'FW',
      nationality: 'England',
      outcomes: [
        { name: 'Aston Villa (stay)', price: 2.00 },
        { name: 'Galatasaray', price: 4.00 },
        { name: 'Borussia Dortmund', price: 5.00 },
        { name: 'Napoli', price: 7.00 },
        { name: 'Marseille', price: 9.00 },
        { name: 'Manchester United (return)', price: 13.00 },
      ],
    },
    {
      player: 'Bruno Fernandes',
      currentClub: 'Manchester United',
      position: 'AM',
      nationality: 'Portugal',
      outcomes: [
        { name: 'Manchester United (stay)', price: 1.60 },
        { name: 'Al-Hilal', price: 5.00 },
        { name: 'Bayern Munich', price: 7.00 },
        { name: 'Juventus', price: 8.00 },
        { name: 'Barcelona', price: 11.00 },
        { name: 'Atlético Madrid', price: 13.00 },
      ],
    },
    {
      player: 'Bernardo Silva',
      currentClub: 'Manchester City',
      position: 'MF',
      nationality: 'Portugal',
      outcomes: [
        { name: 'Manchester City (stay)', price: 1.80 },
        { name: 'Barcelona', price: 3.50 },
        { name: 'Paris Saint-Germain', price: 5.00 },
        { name: 'Al-Qadsiah', price: 7.00 },
        { name: 'Atletico Madrid', price: 9.00 },
        { name: 'Real Madrid', price: 13.00 },
      ],
    },
    {
      player: 'Trent Alexander-Arnold',
      currentClub: 'Real Madrid',
      position: 'RB',
      nationality: 'England',
      outcomes: [
        { name: 'Real Madrid (stay)', price: 1.40 },
        { name: 'Liverpool (return)', price: 8.00 },
        { name: 'Manchester City', price: 17.00 },
        { name: 'Chelsea', price: 21.00 },
        { name: 'Newcastle United', price: 29.00 },
      ],
    },
    {
      player: 'Rafael Leão',
      currentClub: 'AC Milan',
      position: 'FW',
      nationality: 'Portugal',
      outcomes: [
        { name: 'AC Milan (stay)', price: 2.00 },
        { name: 'Chelsea', price: 4.00 },
        { name: 'Manchester City', price: 5.00 },
        { name: 'Real Madrid', price: 7.00 },
        { name: 'Barcelona', price: 8.00 },
        { name: 'Arsenal', price: 9.00 },
        { name: 'Liverpool', price: 11.00 },
      ],
    },
    {
      player: 'Declan Rice',
      currentClub: 'Arsenal',
      position: 'MF',
      nationality: 'England',
      outcomes: [
        { name: 'Arsenal (stay)', price: 1.15 },
        { name: 'Real Madrid', price: 11.00 },
        { name: 'Manchester City', price: 13.00 },
        { name: 'Barcelona', price: 17.00 },
        { name: 'Bayern Munich', price: 21.00 },
      ],
    },
    {
      player: 'Gavi',
      currentClub: 'Barcelona',
      position: 'MF',
      nationality: 'Spain',
      outcomes: [
        { name: 'Barcelona (stay)', price: 1.25 },
        { name: 'Manchester City', price: 11.00 },
        { name: 'Bayern Munich', price: 17.00 },
        { name: 'Real Madrid', price: 21.00 },
        { name: 'Atletico Madrid', price: 29.00 },
      ],
    },
    {
      player: 'Antoine Griezmann',
      currentClub: 'Atletico Madrid',
      position: 'FW',
      nationality: 'France',
      outcomes: [
        { name: 'Atletico Madrid (stay)', price: 1.80 },
        { name: 'Inter Miami', price: 4.50 },
        { name: 'Al-Nassr', price: 5.00 },
        { name: 'MLS (other)', price: 7.00 },
        { name: 'Galatasaray', price: 9.00 },
        { name: 'Retire / End career', price: 11.00 },
      ],
    },
    {
      player: 'Dani Olmo',
      currentClub: 'Barcelona',
      position: 'AM',
      nationality: 'Spain',
      outcomes: [
        { name: 'Barcelona (stay)', price: 1.60 },
        { name: 'Bayern Munich', price: 5.00 },
        { name: 'Manchester City', price: 7.00 },
        { name: 'Chelsea', price: 9.00 },
        { name: 'Arsenal', price: 11.00 },
        { name: 'Liverpool', price: 13.00 },
      ],
    },
    {
      player: 'Marcus Thuram',
      currentClub: 'Inter Milan',
      position: 'FW',
      nationality: 'France',
      outcomes: [
        { name: 'Inter Milan (stay)', price: 1.70 },
        { name: 'Paris Saint-Germain', price: 4.00 },
        { name: 'Chelsea', price: 5.50 },
        { name: 'Manchester United', price: 7.00 },
        { name: 'Arsenal', price: 8.00 },
        { name: 'Bayern Munich', price: 11.00 },
      ],
    },
    {
      player: 'Ivan Toney',
      currentClub: 'Al-Ahli',
      position: 'FW',
      nationality: 'England',
      outcomes: [
        { name: 'Premier League return', price: 2.50 },
        { name: 'Al-Ahli (stay)', price: 3.00 },
        { name: 'Crystal Palace', price: 5.00 },
        { name: 'Everton', price: 7.00 },
        { name: 'Newcastle United', price: 8.00 },
        { name: 'Nottingham Forest', price: 11.00 },
        { name: 'West Ham', price: 13.00 },
      ],
    },
    {
      player: 'Ruben Neves',
      currentClub: 'Al-Hilal',
      position: 'MF',
      nationality: 'Portugal',
      outcomes: [
        { name: 'Al-Hilal (stay)', price: 1.90 },
        { name: 'Barcelona', price: 5.00 },
        { name: 'Manchester United', price: 6.00 },
        { name: 'Juventus', price: 7.00 },
        { name: 'Atletico Madrid', price: 9.00 },
        { name: 'Inter Milan', price: 11.00 },
      ],
    },
    {
      player: 'Dominik Szoboszlai',
      currentClub: 'Liverpool',
      position: 'MF',
      nationality: 'Hungary',
      outcomes: [
        { name: 'Liverpool (stay)', price: 1.40 },
        { name: 'Bayern Munich', price: 7.00 },
        { name: 'Real Madrid', price: 9.00 },
        { name: 'Barcelona', price: 11.00 },
        { name: 'Juventus', price: 13.00 },
        { name: 'Atletico Madrid', price: 17.00 },
      ],
    },
    {
      player: 'Federico Chiesa',
      currentClub: 'Liverpool',
      position: 'FW',
      nationality: 'Italy',
      outcomes: [
        { name: 'Liverpool (stay)', price: 2.25 },
        { name: 'Juventus (return)', price: 3.00 },
        { name: 'AC Milan', price: 5.00 },
        { name: 'Inter Milan', price: 6.00 },
        { name: 'Roma', price: 8.00 },
        { name: 'Napoli', price: 9.00 },
        { name: 'Atletico Madrid', price: 11.00 },
      ],
    },
    {
      player: 'Nuno Mendes',
      currentClub: 'Paris Saint-Germain',
      position: 'LB',
      nationality: 'Portugal',
      outcomes: [
        { name: 'PSG (stay)', price: 1.80 },
        { name: 'Manchester City', price: 4.50 },
        { name: 'Liverpool', price: 5.50 },
        { name: 'Barcelona', price: 7.00 },
        { name: 'Real Madrid', price: 8.00 },
        { name: 'Arsenal', price: 11.00 },
      ],
    },
    {
      player: 'Alejandro Garnacho',
      currentClub: 'Manchester United',
      position: 'FW',
      nationality: 'Argentina',
      outcomes: [
        { name: 'Manchester United (stay)', price: 1.90 },
        { name: 'Chelsea', price: 4.00 },
        { name: 'Atletico Madrid', price: 5.00 },
        { name: 'Napoli', price: 6.00 },
        { name: 'Real Madrid', price: 8.00 },
        { name: 'Barcelona', price: 11.00 },
        { name: 'Arsenal', price: 13.00 },
      ],
    },
    {
      player: 'Joao Felix',
      currentClub: 'Chelsea',
      position: 'FW',
      nationality: 'Portugal',
      outcomes: [
        { name: 'Chelsea (stay)', price: 2.75 },
        { name: 'Atletico Madrid (return)', price: 3.50 },
        { name: 'Barcelona', price: 4.00 },
        { name: 'Juventus', price: 6.00 },
        { name: 'AC Milan', price: 7.00 },
        { name: 'PSG', price: 9.00 },
        { name: 'Bayern Munich', price: 11.00 },
      ],
    },
    {
      player: 'Matthijs de Ligt',
      currentClub: 'Manchester United',
      position: 'CB',
      nationality: 'Netherlands',
      outcomes: [
        { name: 'Manchester United (stay)', price: 2.00 },
        { name: 'Bayern Munich', price: 3.00 },
        { name: 'Chelsea', price: 5.00 },
        { name: 'Juventus (return)', price: 6.00 },
        { name: 'Barcelona', price: 8.00 },
        { name: 'Real Madrid', price: 11.00 },
      ],
    },
    {
      player: 'Rayan Cherki',
      currentClub: 'Lyon',
      position: 'AM',
      nationality: 'France',
      outcomes: [
        { name: 'Manchester City', price: 3.00 },
        { name: 'Liverpool', price: 3.50 },
        { name: 'Arsenal', price: 4.00 },
        { name: 'PSG', price: 4.50 },
        { name: 'Lyon (stay)', price: 5.00 },
        { name: 'Bayern Munich', price: 6.00 },
        { name: 'Real Madrid', price: 8.00 },
        { name: 'Chelsea', price: 9.00 },
      ],
    },
    {
      player: 'Karim Adeyemi',
      currentClub: 'Borussia Dortmund',
      position: 'FW',
      nationality: 'Germany',
      outcomes: [
        { name: 'Liverpool', price: 3.00 },
        { name: 'Chelsea', price: 3.50 },
        { name: 'Arsenal', price: 4.50 },
        { name: 'Borussia Dortmund (stay)', price: 5.00 },
        { name: 'Bayern Munich', price: 6.00 },
        { name: 'Real Madrid', price: 9.00 },
        { name: 'Barcelona', price: 11.00 },
      ],
    },
    {
      player: 'Sandro Tonali',
      currentClub: 'Newcastle United',
      position: 'MF',
      nationality: 'Italy',
      outcomes: [
        { name: 'Newcastle United (stay)', price: 1.50 },
        { name: 'AC Milan (return)', price: 7.00 },
        { name: 'Juventus', price: 9.00 },
        { name: 'Inter Milan', price: 11.00 },
        { name: 'Barcelona', price: 13.00 },
        { name: 'Real Madrid', price: 17.00 },
      ],
    },
    {
      player: 'Lautaro Martínez',
      currentClub: 'Inter Milan',
      position: 'FW',
      nationality: 'Argentina',
      outcomes: [
        { name: 'Inter Milan (stay)', price: 1.30 },
        { name: 'Chelsea', price: 8.00 },
        { name: 'Liverpool', price: 9.00 },
        { name: 'Real Madrid', price: 13.00 },
        { name: 'Barcelona', price: 17.00 },
        { name: 'Al-Hilal', price: 23.00 },
      ],
    },
    {
      player: 'Pedri',
      currentClub: 'Barcelona',
      position: 'MF',
      nationality: 'Spain',
      outcomes: [
        { name: 'Barcelona (stay)', price: 1.15 },
        { name: 'Manchester City', price: 13.00 },
        { name: 'Real Madrid', price: 17.00 },
        { name: 'Liverpool', price: 21.00 },
        { name: 'Bayern Munich', price: 29.00 },
      ],
    },
    {
      player: 'Cody Gakpo',
      currentClub: 'Liverpool',
      position: 'FW',
      nationality: 'Netherlands',
      outcomes: [
        { name: 'Liverpool (stay)', price: 1.60 },
        { name: 'Atletico Madrid', price: 6.00 },
        { name: 'Chelsea', price: 7.00 },
        { name: 'Arsenal', price: 8.00 },
        { name: 'Newcastle United', price: 9.00 },
        { name: 'Barcelona', price: 11.00 },
        { name: 'PSG', price: 13.00 },
      ],
    },
    {
      player: 'Bryan Mbeumo',
      currentClub: 'Brentford',
      position: 'FW',
      nationality: 'Cameroon',
      outcomes: [
        { name: 'Arsenal', price: 2.50 },
        { name: 'Chelsea', price: 3.00 },
        { name: 'Newcastle United', price: 3.50 },
        { name: 'Brentford (stay)', price: 4.00 },
        { name: 'Manchester United', price: 5.00 },
        { name: 'Liverpool', price: 6.00 },
        { name: 'Atletico Madrid', price: 9.00 },
      ],
    },
  ],
  1: [
    {
      player: 'Bukayo Saka',
      currentClub: 'Arsenal',
      position: 'FW',
      outcomes: [
        { name: 'Arsenal (stay)', price: 1.10 },
        { name: 'Real Madrid', price: 9.00 },
        { name: 'Manchester City', price: 12.00 },
        { name: 'Bayern Munich', price: 15.00 },
      ],
    },
    {
      player: 'Jadon Sancho',
      currentClub: 'Chelsea',
      position: 'FW',
      outcomes: [
        { name: 'Chelsea (stay)', price: 2.50 },
        { name: 'Borussia Dortmund', price: 3.50 },
        { name: 'Juventus', price: 5.00 },
        { name: 'Manchester United', price: 6.00 },
      ],
    },
  ],
  2: [
    {
      player: 'Vinicius Jr',
      currentClub: 'Real Madrid',
      position: 'FW',
      outcomes: [
        { name: 'Real Madrid (stay)', price: 1.30 },
        { name: 'Al-Hilal', price: 5.00 },
        { name: 'Manchester City', price: 9.00 },
        { name: 'Paris Saint-Germain', price: 13.00 },
      ],
    },
    {
      player: 'Trent Alexander-Arnold',
      currentClub: 'Real Madrid',
      position: 'RB',
      outcomes: [
        { name: 'Real Madrid (stay)', price: 1.40 },
        { name: 'Liverpool (return)', price: 8.00 },
        { name: 'Manchester City', price: 17.00 },
      ],
    },
  ],
};

export function getTransferOddsForLeague(leagueId: number): TransferOddsEntry[] {
  const leagueSpecific = (STATIC_TRANSFER_ODDS as Record<number | 'global', TransferOddsEntry[]>)[leagueId] || [];
  const global = STATIC_TRANSFER_ODDS.global;
  const seen = new Set(leagueSpecific.map(e => e.player));
  return [...leagueSpecific, ...global.filter(e => !seen.has(e.player))];
}
