import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '3 Daily Sure Odds Strategy | Free Sure Odds Today | Daily Winning Tips | Betcheza',
  description: 'Get 3 sure odds daily with our proven 7-day compounding football betting strategy. Free sure odds today, daily football predictions, and AI-powered winning tips. Grow KES 1,000 to KES 108,000 in one week. Best free betting tips Kenya, SportPesa & Betika jackpot picks, and sure 3 odds accumulator — updated every day.',
  keywords: [
    // Core page terms
    '3 daily sure odds',
    '3 sure odds today',
    '3 odds today free',
    'sure 3 odds daily',
    'sure 3 odds today free',
    'free sure odds today',
    'sure odds today',
    'daily sure odds',
    '3 daily odds',
    '3 odds daily',
    'sure odds',
    // Strategy / compounding
    '3 odds strategy',
    'daily 3 odds strategy',
    'compounding betting strategy',
    'football betting strategy',
    'bankroll management betting',
    'grow KES 1000 betting',
    'betting bankroll growth Kenya',
    'accumulator betting strategy',
    '7 day betting challenge',
    // Tips / predictions
    'daily betting tips',
    'daily football predictions',
    'football betting tips today',
    'soccer predictions today',
    'sure football predictions',
    'sure tips today',
    'winning tips today',
    'today football tips',
    'best football predictions today',
    'free football tips today',
    'free soccer predictions',
    'correct score predictions',
    'correct score tips today',
    '100 sure odds',
    'safe betting tips',
    // Markets
    'over 2.5 goals tips',
    'both teams to score tips',
    'btts tips today',
    'over under tips today',
    'daily football accumulator',
    'accumulator tips today',
    'multi bet tips',
    'treble bet tips today',
    'value betting tips',
    'profitable betting tips',
    'sure bets today',
    'daily sure bets',
    'daily winning odds',
    'best daily odds',
    'daily odds prediction',
    'today sure odds',
    'winning football tips',
    'sure odds prediction',
    'best daily football tips',
    'football tips free',
    // Kenya / local bookmakers
    'football predictions Kenya',
    'sure odds Kenya',
    'betting tips Kenya',
    'sports betting Kenya',
    'SportPesa tips today',
    'SportPesa jackpot tips',
    'Betika tips today',
    'Betika jackpot predictions',
    'mega jackpot predictions',
    'jackpot tips today Kenya',
    'free betting tips Kenya',
    'daily odds tips Kenya',
    'best tipsters Kenya',
    'football tips Africa',
    // Brand
    'betcheza predictions',
    'betcheza strategy',
    'betcheza sure odds',
    'betcheza tips today',
    // Long-tail
    'betting tips that win',
    'sure football predictions today',
    '3 sure games today',
    '3 sure predictions today',
    '3 correct score predictions today',
    'best 3 odds today',
    'daily 3 correct picks',
    'sure 3 correct score',
    'free 3 odds accumulator today',
    'football accumulator tips today free',
    'highest odds sure bet today',
    'best value bets today football',
    'AI football predictions today',
    'AI betting tips Kenya',
  ],
  openGraph: {
    title: '3 Daily Sure Odds Winning Strategy | Free Football Predictions | Betcheza',
    description: 'Proven 7-day compounding strategy with 3 daily sure odds. Grow KES 1,000 to KES 108,000 in one week. Free AI-powered football predictions and jackpot tips updated every day for Kenya, SportPesa, and Betika.',
    type: 'website',
    siteName: 'Betcheza',
    url: 'https://betcheza.co.ke/strategy',
  },
  twitter: {
    card: 'summary_large_image',
    title: '3 Daily Sure Odds Winning Strategy | Free Football Predictions | Betcheza',
    description: 'Proven 7-day compounding strategy with 3 daily sure odds. Free football tips updated daily — SportPesa, Betika, and jackpot predictions for Kenya.',
  },
  alternates: {
    canonical: 'https://betcheza.co.ke/strategy',
  },
};

export default function StrategyLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
