import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '3 Daily Sure Odds Strategy | Daily Sure Odds | Free Sure Odds Today | Betcheza',
  description: 'Get 3 daily sure odds with our proven 7-day compounding football betting strategy. Best daily sure odds, correct score predictions, and winning tips. Grow KES 1,000 to KES 108,000 in one week.',
  keywords: [
    '3 daily sure odds',
    '3 daily odds',
    'daily sure odds',
    'sure odds today',
    'free sure odds today',
    'daily winning odds',
    'sure odds',
    'daily betting tips',
    'sure bets today',
    'football betting tips today',
    'soccer predictions today',
    'correct score predictions',
    'sure 3 odds daily',
    'winning football tips',
    'best daily odds',
    'daily odds prediction',
    'today sure odds',
    'daily 3 odds strategy',
    'best football predictions today',
    'sure odds prediction',
    'free football tips today',
    'football predictions Kenya',
    'sure odds Kenya',
    'daily sure bets',
    'accumulator tips today',
    'over 2.5 goals tips',
    'both teams to score tips',
    'daily football accumulator',
    'winning tips today',
    'football betting strategy',
    'compounding betting strategy',
    'bankroll management betting',
    'profitable betting tips',
    'betcheza predictions',
    'betcheza strategy',
    'daily odds tips Kenya',
    'best tipsters Kenya',
    'correct score tips today',
    '100 sure odds',
    'safe betting tips',
    'daily football predictions',
    'free soccer predictions',
    'today football tips',
    '3 odds daily',
    'best daily football tips',
    'football tips free',
    'sure tips today',
    'mega jackpot predictions',
    'multi bet tips',
    'sports betting Kenya',
    'betting tips that win',
    'sure football predictions',
    'value betting tips',
  ],
  openGraph: {
    title: '3 Daily Sure Odds Winning Strategy | Betcheza',
    description: 'Proven 7-day compounding strategy with 3 daily sure odds. Grow KES 1,000 to KES 108,000 in one week with our AI-powered football predictions.',
    type: 'website',
    siteName: 'Betcheza',
    url: 'https://betcheza.co.ke/strategy',
  },
  twitter: {
    card: 'summary_large_image',
    title: '3 Daily Sure Odds Winning Strategy | Betcheza',
    description: 'Proven 7-day compounding strategy with 3 daily sure odds. Expert football predictions updated daily.',
  },
  alternates: {
    canonical: 'https://betcheza.co.ke/strategy',
  },
};

export default function StrategyLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
