import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Best Jackpot Predictions Kenya Today | Free AI Tips — Betcheza',
  description: 'Get the best free jackpot predictions in Kenya today — AI-powered tips for SportPesa Mega Jackpot (17 games), SportPesa Midweek Jackpot, Betika Grand Jackpot, OdiBets Jackpot Bonanza, Mozzartbet Mega Jackpot and Betin jackpot. Most accurate jackpot banker picks updated daily.',
  keywords: [
    'best jackpot predictions Kenya',
    'Kenya jackpot predictions today',
    'free jackpot predictions Kenya',
    'most accurate jackpot tips Kenya',
    'jackpot predictions today Kenya',
    'sure jackpot prediction Kenya',
    'jackpot tips Kenya free',
    'jackpot free picks Kenya',
    'winning jackpot tips Kenya',
    'jackpot banker Kenya today',
    'jackpot analysis Kenya',
    'AI jackpot tips Kenya',
    'how to win jackpot Kenya',
    'SportPesa jackpot predictions',
    'SportPesa Mega Jackpot predictions',
    'SportPesa Mega Jackpot prediction today',
    'SportPesa Mega Jackpot tips today',
    'SportPesa Mega Jackpot 17 games',
    'mega jackpot prediction 17 games',
    'mega jackpot prediction today',
    'mega jackpot tips today Kenya',
    'mega jackpot banker today',
    'SportPesa Midweek Jackpot predictions',
    'SportPesa Midweek Jackpot tips today',
    'SportPesa Midweek Jackpot banker',
    'SportPesa jackpot games today',
    'SportPesa jackpot this week',
    'Betika jackpot predictions',
    'Betika Grand Jackpot predictions',
    'Betika Grand Jackpot tips today',
    'Betika Grand Jackpot banker',
    'Betika jackpot banker today',
    'Betika Midweek Jackpot predictions',
    'Betika Daily Jackpot predictions',
    'OdiBets jackpot predictions',
    'OdiBets Jackpot Bonanza predictions',
    'OdiBets jackpot tips today',
    'Betin jackpot predictions',
    'Betin Grand Jackpot predictions Kenya',
    'Mozzartbet jackpot predictions',
    'Mozzartbet Mega Jackpot predictions',
    'Mozzartbet jackpot tips Kenya',
    'best betting tips Kenya jackpot',
    'jackpot winners Kenya',
    'Betcheza jackpot',
  ],
  openGraph: {
    title: 'Kenya Jackpot Predictions | Free AI Tips — Betcheza',
    description: 'Get free AI predictions for SportPesa Mega & Midweek Jackpot (17 games), Betika Grand Jackpot, OdiBets, Betin and Mozzartbet. Banker picks and confidence ratings updated daily.',
    url: 'https://betcheza.co.ke/jackpots',
    type: 'website',
    siteName: 'Betcheza',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Kenya Jackpot Predictions Today | Betcheza',
    description: 'Free AI jackpot tips for SportPesa Mega Jackpot (17 games), Betika Grand Jackpot, OdiBets, Betin & Mozzartbet. Updated daily.',
  },
  alternates: { canonical: 'https://betcheza.co.ke/jackpots' },
  robots: { index: true, follow: true },
};

export default function JackpotsLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
