import { NextRequest, NextResponse } from 'next/server';
import { query } from '@/lib/db';
import {
  createNotification,
  listPushSubscriptions,
  listAllUserIds,
} from '@/lib/notification-store';
import { fileStoreGet, fileStoreSet } from '@/lib/file-store';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

interface StrategyPick {
  id: string;
  homeTeam: string;
  awayTeam: string;
  league: string;
  matchTime: string;
  pick: string;
  market: string;
  odds: number;
  confidence: 'High' | 'Medium' | 'Low';
  reasoning: string;
  result: 'pending' | 'win' | 'loss';
}

interface SentLog {
  date: string;
  pushCount: number;
  inAppCount: number;
  pick: string;
}

function todayEAT(): string {
  // EAT = UTC+3
  const now = new Date();
  const eat = new Date(now.getTime() + 3 * 60 * 60 * 1000);
  return eat.toISOString().slice(0, 10);
}

function confidenceScore(p: StrategyPick): number {
  if (p.confidence === 'High') return 3;
  if (p.confidence === 'Medium') return 2;
  return 1;
}

function bestPick(picks: StrategyPick[]): StrategyPick {
  return picks.slice().sort((a, b) => {
    const cs = confidenceScore(b) - confidenceScore(a);
    if (cs !== 0) return cs;
    // Among equal confidence, prefer odds in 1.60–2.20 sweet-spot
    const aScore = Math.abs(a.odds - 1.90);
    const bScore = Math.abs(b.odds - 1.90);
    return aScore - bScore;
  })[0];
}

async function getTodayPicks(): Promise<StrategyPick[] | null> {
  const dateStr = todayEAT();

  // Try DB first
  try {
    const r = await query<{ picks: string | null }>(
      'SELECT picks FROM daily_strategy WHERE date = ? LIMIT 1',
      [dateStr],
    );
    if (r.rows.length > 0 && r.rows[0].picks) {
      const parsed = JSON.parse(r.rows[0].picks) as StrategyPick[];
      if (Array.isArray(parsed) && parsed.length > 0) return parsed;
    }
  } catch { /* no DB or table not yet created */ }

  // Try file store fallback
  const weekMonday = (() => {
    const d = new Date();
    const day = d.getDay();
    d.setDate(d.getDate() - (day === 0 ? 6 : day - 1));
    return d.toISOString().slice(0, 10);
  })();
  const stored = fileStoreGet<{ days?: Array<{ date: string; picks?: StrategyPick[] }> } | null>(
    `strategy-week-${weekMonday}`,
    null,
  );
  if (stored?.days) {
    const day = stored.days.find(d => d.date === dateStr);
    if (day?.picks && day.picks.length > 0) return day.picks;
  }

  return null;
}

export async function GET(req: NextRequest) {
  const authHeader = req.headers.get('authorization');
  const cronSecret = process.env.CRON_SECRET || 'betcheza-cron-2024';
  if (authHeader !== `Bearer ${cronSecret}`) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const dateStr = todayEAT();
  const LOG_KEY = 'tip-of-the-day-sent';

  // Idempotency — only send once per day
  const log = fileStoreGet<SentLog | null>(LOG_KEY, null);
  if (log?.date === dateStr) {
    return NextResponse.json({
      ok: true,
      skipped: true,
      reason: 'Already sent today',
      date: dateStr,
      pushCount: log.pushCount,
      inAppCount: log.inAppCount,
    });
  }

  // Fetch today's picks (generated by the daily-strategy cron)
  const picks = await getTodayPicks();
  if (!picks || picks.length === 0) {
    return NextResponse.json({
      ok: false,
      reason: 'No picks available yet for today. Run daily-strategy first.',
      date: dateStr,
    });
  }

  const pick = bestPick(picks);
  const combinedOdds = picks.reduce((acc, p) => acc * p.odds, 1);

  const title = `🔥 Tip of the Day — ${pick.homeTeam} vs ${pick.awayTeam}`;
  const body = `${pick.pick} @ ${pick.odds.toFixed(2)} (${pick.market}) · ${pick.league}`;
  const fullBody =
    picks.length === 1
      ? body
      : `${body} — Today's ${picks.length}-pick accumulator @ ${combinedOdds.toFixed(2)} combined odds`;
  const link = '/strategy';

  let pushCount = 0;
  let inAppCount = 0;

  // ── Web push ──────────────────────────────────────────────────────────────
  try {
    const { sendPushToSubscription } = await import('@/lib/push-sender');
    const subs = await listPushSubscriptions();
    const results = await Promise.allSettled(
      subs.map(sub =>
        sendPushToSubscription(sub, {
          title,
          body: fullBody,
          url: link,
          tag: 'tip-of-the-day',
          icon: '/icon-192.png',
          badge: '/icon-72.png',
          requireInteraction: false,
        }).then(() => { pushCount++; }),
      ),
    );
    const failed = results.filter(r => r.status === 'rejected').length;
    if (failed > 0) console.warn(`[tip-of-the-day] ${failed} push(es) failed`);
  } catch (e) {
    console.warn('[tip-of-the-day] web push error:', e instanceof Error ? e.message : e);
  }

  // ── In-app notifications for every registered user ─────────────────────
  try {
    const allUserIds = await listAllUserIds();
    const pushSubs = await listPushSubscriptions();
    const pushUserIds = pushSubs.map(s => s.userId).filter((id): id is number => !!id);
    const userIds = Array.from(new Set([...allUserIds, ...pushUserIds]));

    for (const uid of userIds) {
      await createNotification({
        userId: uid,
        type: 'tip_of_the_day',
        title,
        content: fullBody,
        link,
        channel: 'inapp',
      });
      inAppCount++;
    }
  } catch (e) {
    console.warn('[tip-of-the-day] in-app notification error:', e instanceof Error ? e.message : e);
  }

  // ── Persist sent log ──────────────────────────────────────────────────────
  fileStoreSet<SentLog>(LOG_KEY, { date: dateStr, pushCount, inAppCount, pick: pick.pick });

  console.log(
    `[tip-of-the-day] Sent for ${dateStr}: "${pick.pick} @ ${pick.odds}" — ${pushCount} push, ${inAppCount} in-app`,
  );

  return NextResponse.json({
    ok: true,
    date: dateStr,
    pick: { match: `${pick.homeTeam} vs ${pick.awayTeam}`, pick: pick.pick, odds: pick.odds, market: pick.market },
    picks: picks.length,
    combinedOdds: parseFloat(combinedOdds.toFixed(2)),
    pushCount,
    inAppCount,
  });
}
